/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.VistaInscripciones;

import Controls.AlumnoData;
import Controls.Conexion;
import Controls.CursadaData;
import Controls.MateriaData;
import Models.Alumno;
import Models.Cursada;
import Models.Materia;
import java.util.ArrayList;

/**
 *
 * @author Isaias
 */
public class inscripciones extends javax.swing.JInternalFrame {

    Conexion con = new Conexion();

    MateriaData md = new MateriaData(con);

    AlumnoData ad = new AlumnoData(con);

    CursadaData cd = new CursadaData(con);

    public inscripciones() {
        initComponents();
        llenarComboAlumno();
        llenarComboMateria();
    }

    public void limpiarCampos() {
        jComboAlumno.setSelectedIndex(-1);
        jComboMateria.setSelectedIndex(-1);
    }

    public void llenarComboAlumno() {
        ArrayList<Alumno> listaAlumnos = (ArrayList<Alumno>) ad.listarAlumnos();

        for (Alumno a : listaAlumnos) {
            jComboAlumno.addItem(a);
        }
        jComboAlumno.setSelectedIndex(-1);
    }

    public void llenarComboMateria() {
        ArrayList<Materia> listaMaterias = (ArrayList<Materia>) md.listarMaterias();

        for (Materia m : listaMaterias) {
            jComboMateria.addItem(m);
        }
        jComboMateria.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboAlumno = new javax.swing.JComboBox<>();
        jComboMateria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonInscribir = new javax.swing.JButton();
        jButtonDesinscribir = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Formulario de Inscripción");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Formulario de Inscripción");

        jComboAlumno.setToolTipText("Seleccionar Alumno.");
        jComboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlumnoActionPerformed(evt);
            }
        });

        jComboMateria.setToolTipText("Seleccionar Materia.");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Materia:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Alumno:");

        jButtonInscribir.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonInscribir.setText("Inscribir");
        jButtonInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscribirActionPerformed(evt);
            }
        });

        jButtonDesinscribir.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonDesinscribir.setText("Desinscribir");
        jButtonDesinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesinscribirActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45)
                                .addComponent(jComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(42, 42, 42)
                                .addComponent(jComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonInscribir)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonDesinscribir)
                                    .addGap(28, 28, 28)
                                    .addComponent(jButtonSalir))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInscribir)
                    .addComponent(jButtonDesinscribir)
                    .addComponent(jButtonSalir))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAlumnoActionPerformed

    
    //--------------------------REVISAR ESTE BOTON------------------------------
    private void jButtonInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscribirActionPerformed
        // TODO add your handling code here:
        
        //este boton crea inscripciones entre un alumno y una materia 
        
        //la idea es que a una inscripcion no creada la cree, y a una que este creada pero inactiva, la setee a activa
        
        Cursada c = new Cursada();

        Alumno a = (Alumno) jComboAlumno.getSelectedItem();

        Materia m = (Materia) jComboMateria.getSelectedItem();
        
        if (true) {
            //aca deberia actualizar una inscripcion ya creada de inactiva a activa

        } else {
            c.setAlumno(a);
            c.setMateria(m);      //y aca, en caso de no existir esa inscripcion, crearla y agregarla a la cursadaData
            c.setActivo(true);

            cd.guardarInscripcion(c);
        }

        jComboAlumno.setSelectedIndex(-1);
        jComboMateria.setSelectedIndex(-1);

    }//GEN-LAST:event_jButtonInscribirActionPerformed

    private void jButtonDesinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesinscribirActionPerformed
        // TODO add your handling code here:
        Cursada c = new Cursada();

        Alumno a = (Alumno) jComboAlumno.getSelectedItem();

        Materia m = (Materia) jComboMateria.getSelectedItem();

        cd.borrarInscripcion(m.getIdMateria(), a.getIdAlumno());

        jComboAlumno.setSelectedIndex(-1);
        jComboMateria.setSelectedIndex(-1);
    }//GEN-LAST:event_jButtonDesinscribirActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDesinscribir;
    private javax.swing.JButton jButtonInscribir;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<Alumno> jComboAlumno;
    private javax.swing.JComboBox<Materia> jComboMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
